# Generated by Django 4.2.1 on 2023-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_utilizador_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='tarefasconcluidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='tarefascriadas',
            field=models.IntegerField(default=0),
        ),
    ]
