# Generated by Django 4.2.1 on 2023-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_utilizador_datadecriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='datadecriacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
