# Generated by Django 4.2.1 on 2023-05-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_alter_utilizador_datadecriacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='tarefasconcluidas',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='tarefascriadas',
        ),
    ]
