# Generated by Django 4.1.7 on 2023-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_alter_utilizador_datadecriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
