# Generated by Django 4.2.1 on 2023-05-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_utilizador_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='tarefasconcluidas',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='tarefascriadas',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('pouca', 'Pouca'), ('mediana', 'Mediana'), ('alta', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='descricao',
            field=models.TextField(default='Ainda sem descricao ,escreva um pouco sobre si!'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
