# Generated by Django 4.2.1 on 2023-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_alter_utilizador_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
