# Generated by Django 4.2.1 on 2023-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_remove_utilizador_tarefasconcluidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='descricao',
            field=models.TextField(default='Ainda sem descricao, escreva um pouco sobre si!'),
        ),
    ]
