# Generated by Django 4.2.1 on 2023-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_alter_utilizador_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='descricao',
            field=models.TextField(default='Ainda sem descricao, escreva um pouco sobre si!', max_length=30),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
